### ISSUE TITLE
Support sbt 1.0.0

### ISSUE THREAD

**Issue by rleibman** [melezov/sbt-sh#3]
Please :)

**Comment by melezov** [comment]
Will try to do it tonight! :)

**Comment by melezov** [comment]
Finally gave this some love and pushed `0.2.1` against both 0.13.x and 1.x.
Refactored a bit - now it's only 1 line of code :D

**Comment by rleibman** [comment]
From Murphy's laws:
- Every non-trivial program contains at least one bug.
- Every non-trivial program can be simplified by at least one line of code.
The conclusion of the last two laws: Every non trivial program can be simplified to one line of code, and it will contain a bug.

**Comment by rleibman** [comment]
Damn, and I said that as a joke... 
If I just type
```sh```
I get
```
java.lang.ArrayIndexOutOfBoundsException: 0
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1014)
	at sbt.SimpleProcessBuilder.run(ProcessImpl.scala:349)
	at sbt.AbstractProcessBuilder.run(ProcessImpl.scala:126)
	at sbt.AbstractProcessBuilder.$bang(ProcessImpl.scala:154)
	at sbt.Resolvers$.run(Resolvers.scala:132)
	at sbt.Resolvers$.run(Resolvers.scala:125)
	at com.oradian.sbt.SbtShPlugin$$anonfun$shCommand$1.apply(SbtShPlugin.scala:13)
	at com.oradian.sbt.SbtShPlugin$$anonfun$shCommand$1.apply(SbtShPlugin.scala:12)
	at sbt.Command$$anonfun$sbt$Command$$apply1$1$$anonfun$apply$6.apply(Command.scala:71)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.runCmd$1(State.scala:183)
	at sbt.State$$anon$1.process(State.scala:187)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:61)
	at sbt.xMain.run(Main.scala:35)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)```

**Comment by melezov** [comment]
Hahaah - awesome find there!
Not quite sure what the output should be though... Perhaps a "help" of some sort
Please use `sh <arguments>`? :)

**Comment by rleibman** [comment]
Either that, or just nothing (same as pressing enter on the shell)

**Comment by melezov** [comment]
Naw, took the brick-to-the face approach:
https://github.com/melezov/sbt-sh/blob/fd99f29405fdc2f22fb250a446a87ddfaf8811aa/src/main/scala/SbtShPlugin.scala#L33

About to release 0.3.0...

**Comment by rleibman** [comment]
Perfect, thanks!
